Update workflow and other files

diff --git a/.github/workflows/job.yml b/.github/workflows/job.yml
--- a/.github/workflows/job.yml
+++ b/.github/workflows/job.yml
@@ -1,4 +1,4 @@
-name: UCSSMonitor Job
+name: UCSSMonitor Job and Deploy
 
 on:
   push:
@@ -92,3 +92,34 @@ jobs:
         with:
           name: index-html
           path: docs/index.html
+
+  deploy:
+    needs: update_graph
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Download index.html artifact
+        uses: actions/download-artifact@v4.2.1
+        with:
+          name: index-html
+          path: .
+
+      - name: Move index.html to docs directory
+        run: |
+          mkdir -p docs
+          cp index-html/index.html docs/index.html
+
+      - name: Verify index.html exists
+        run: |
+          if [ ! -f docs/index.html ]; then
+            echo "Error: index.html not found in docs directory.";
+            exit 1;
+          fi
+
+      - name: Deploy to GitHub Pages
+        uses: peaceiris/actions-gh-pages@v4
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: docs
